pc:
  host: 172.28.0.1
selmag:
  services:
    catalogue:
      #      uri: lb://selmag-catalogue-service
      uri: http://${pc.host}:8081
      registration-id: keycloak
    feedback:
      #      uri: lb://selmag-feedback-service
      uri: http://${pc.host}:8083
      registration-id: keycloak
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${pc.host}:9000/realms/selmag
      client:
        registration:
          keycloak:
            client-id: customer-service
            client-secret: HDVfSb2LppBicZPOyDrwlCjuoQllwJzD
            authorization-grant-type: client_credentials
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: customer-service
            client-secret: HDVfSb2LppBicZPOyDrwlCjuoQllwJzD
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-service
            client-secret: HDVfSb2LppBicZPOyDrwlCjuoQllwJzD
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://${pc.host}:9000/realms/selmag
            user-name-attribute: preferred_username
management:
  health:
    livenessstate:
      enable: true
    readinessstate:
      enable: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://${pc.host}:8761/eureka/
  instance:
    prefer-ip-address: true
