my:
  name: github_selmag_eureka_service
  
eureka:
  instance:
    hostname: 172.28.0.1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.28.0.1:9000/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: eureka-service
            client-secret: Q2c59snpshD7yHKGCEoUwpOH38GVEsOO
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://172.28.0.1:9000/realms/selmag