pc:
  host: 172.28.0.1
eureka:
  instance:
    hostname: ${pc.host}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: selmag-eureka-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${pc.host}:9000/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: eureka-service
            client-secret: Q2c59snpshD7yHKGCEoUwpOH38GVEsOO
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://${pc.host}:9000/realms/selmag